### ISSUE TITLE
Tried calling: restart() when try to convert the app language 

### ISSUE THREAD

**Issue by mohmmed750** [msayed-net/localize_and_translate#13]
I have a problem, 
when I try to converter the app language, I faced a problem, 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'restart' was called on null.
E/flutter ( 6490): Receiver: null
E/flutter ( 6490): Tried calling: restart()
E/flutter ( 6490): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 6490): #1      LocalizedApp.restart (package:localize_and_translate/src/main.class.dart:258:11)
E/flutter ( 6490): #2      LocalizeAndTranslate.setNewLanguage (package:localize_and_translate/src/main.class.dart:197:20)
E/flutter ( 6490): <asynchronous suspension>
E/flutter ( 6490): #3      _settingsState._onBackPressed.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:erp_accounting_app/drawer_pages/setting.dart:159:32)
E/flutter ( 6490): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)`

this is my code : 

`  translator.setNewLanguage(
                      context,
                      newLanguage: translator.currentLanguage == 'ar' ? 'en' : 'ar',
                      remember: true,
                      restart: true,
                    );`

what is the problem ??

**Comment by msayed-net** [comment]
Please share your `flutter doctor -v` output and initialization code

**Comment by mohmmed750** [comment]
this is the responce of flutter doctor .. 
![image](https://user-images.githubusercontent.com/59219335/99081185-140e4380-25cb-11eb-82f9-bdb3a3ffbba9.png)

and the is the initialization code

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await translator.init(
    localeDefault: LocalizationDefaultType.device,
    languagesList: <String>['ar', 'en'],
    assetsDirectory: 'assets/langs/',
  ); `

**Comment by msayed-net** [comment]
okay, thanks for the details I will check it

**Comment by msayed-net** [comment]
Please test version 3.0.3, I believe it's solved

**Comment by mjmon** [comment]
I still have the same issue using latest version `localize_and_translate: ^3.0.3`

**Comment by mjmon** [comment]
This is my code .

initialize
```

  WidgetsFlutterBinding.ensureInitialized();

  await translator.init(
    localeDefault: LocalizationDefaultType.device,
    languagesList: <String>['da', 'en'],
    assetsDirectory: 'language/',
  );
```

```
translator.setNewLanguage(
  context,
  newLanguage:
      translator.currentLanguage == 'en' ? 'da' : 'en',
  restart: true,
);
```

**Comment by msayed-net** [comment]
@mjmon did you wrap your main class inside `runApp()` method with `LocalizedApp()` !

[example](https://github.com/msayed-net/localize_and_translate#initialization)

**Comment by mjmon** [comment]
yes `LocalizedApp()` fixed the error. but does not automatically trigger the localization on my end as I need it without restarting the App state.

**Comment by msayed-net** [comment]
Glad to hear that, thanks for sharing..
