### ISSUE TITLE
Tried calling: restart() when i try to convert the app language

### ISSUE THREAD

**Issue by mohmmed750** [msayed-net/localize_and_translate#14]
I have a problem, 
when I try to converter the app language, I faced a problem, 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'restart' was called on null.
E/flutter ( 6490): Receiver: null
E/flutter ( 6490): Tried calling: restart()
E/flutter ( 6490): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 6490): #1      LocalizedApp.restart (package:localize_and_translate/src/main.class.dart:258:11)
E/flutter ( 6490): #2      LocalizeAndTranslate.setNewLanguage (package:localize_and_translate/src/main.class.dart:197:20)
E/flutter ( 6490): <asynchronous suspension>
E/flutter ( 6490): #3      _settingsState._onBackPressed.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:erp_accounting_app/drawer_pages/setting.dart:159:32)
E/flutter ( 6490): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)`

this is my code : 

`  translator.setNewLanguage(
                      context,
                      newLanguage: translator.currentLanguage == 'ar' ? 'en' : 'ar',
                      remember: true,
                      restart: true,
                    );`

what is the problem ??

**Comment by msayed-net** [comment]
This is duplicated with [#13 ](https://github.com/msayed-net/localize_and_translate/issues/13#issue-741487235) and closing it.
