### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'restart' was called on null.

### ISSUE THREAD

**Issue by ThamerRamzi** [msayed-net/localize_and_translate#15]
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'restart' was called on null.
Receiver: null
Tried calling: restart()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LocalizedApp.restart (package:localize_and_translate/src/main.class.dart:258:11)
#2      LocalizeAndTranslate.setNewLanguage (package:localize_and_translate/src/main.class.dart:197:20)
<asynchronous suspension>

**Comment by ThamerRamzi** [comment]
You wasted my time by this bug : (

**Comment by msayed-net** [comment]
Please test version 3.0.3, I believe it's solved
