### ISSUE TITLE
Text direction doesnt get updated when changing app locale with setLanguage()

### ISSUE THREAD

**Issue by amini-rezza** [msayed-net/localize_and_translate#16]
The app should be killed and restarted again after changing language with setLanguage() for the text direction to update(RTL ,LTR). The restart filed does restart the app and updates text but doesn't update text direction

**Comment by msayed-net** [comment]
Can you provide output of the terminal command `flutter doctor -v` !

**Comment by amini-rezza** [comment]
Here you are :
 Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

**Comment by amini-rezza** [comment]
Found the issue.I had put LocalizedApp parent of MaterialApp instead of MyApp.By correcting it, it works flawless.

**Comment by msayed-net** [comment]
Thanks for sharing the solution.
