### ISSUE TITLE
I Cant Use Restart true When iam setting new language Please How Can i do that 

### ISSUE THREAD

**Issue by Abodysoma2021** [msayed-net/localize_and_translate#28]
![Screen Shot 2021-12-23 at 9 29 54 AM](https://user-images.githubusercontent.com/79199392/147204721-1ac34e35-8ed8-43bc-ac1d-9cc9bb6c7e2a.png)

**Comment by msayed-net** [comment]
Could you share your `main()` implementation please

**Comment by Abodysoma2021** [comment]
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initilize Localization With localize_and_translate Package
  await translator.init(
    localeType: LocalizationDefaultType.device,
    languagesList: <String>['ar', 'en'],
    assetsDirectory: 'assets/lang/',
  );
  runApp(LocalizedApp(child: MyApp()));
}

//hello
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    //Wrap Application With Getx Package
    return GetMaterialApp(
      initialBinding: Binding(),
      // initialRoute:  homeController.initScreen == 0 ? OnboardingScreen() :HomeView(),
      debugShowCheckedModeBanner: false,
      title: 'Moya App',
      theme: ThemeData(
          primarySwatch: AppStyles.primaryColor,
          scaffoldBackgroundColor: AppStyles.backgroundColor,
          fontFamily: 'Sfpro'),
      home: ControlView(),
      localizationsDelegates: translator.delegates, // Android + iOS Delegates
      locale: translator.activeLocale, // Active locale
      supportedLocales: translator.locals(), // Locals list
    );
  }
}

**Comment by Abodysoma2021** [comment]
> Could you share your `main()` implementation please

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initilize Localization With localize_and_translate Package
  await translator.init(
    localeType: LocalizationDefaultType.device,
    languagesList: <String>['ar', 'en'],
    assetsDirectory: 'assets/lang/',
  );
  runApp(LocalizedApp(child: MyApp()));
}

//hello
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    //Wrap Application With Getx Package
    return GetMaterialApp(
      initialBinding: Binding(),
      // initialRoute:  homeController.initScreen == 0 ? OnboardingScreen() :HomeView(),
      debugShowCheckedModeBanner: false,
      title: 'Moya App',
      theme: ThemeData(
          primarySwatch: AppStyles.primaryColor,
          scaffoldBackgroundColor: AppStyles.backgroundColor,
          fontFamily: 'Sfpro'),
      home: ControlView(),
      localizationsDelegates: translator.delegates, // Android + iOS Delegates
      locale: translator.activeLocale, // Active locale
      supportedLocales: translator.locals(), // Locals list
    );
  }
}

**Comment by msayed-net** [comment]
Thanks for sharing, 

and how do you call `setNewLanguage()`, what parameters did you use.

**Comment by Abodysoma2021** [comment]
![Screen Shot 2021-12-28 at 9 59 21 AM](https://user-images.githubusercontent.com/79199392/147543003-3b95aac2-2b85-416f-afb7-3a46697494a0.png)


> Thanks for sharing,
> 
> and how do you call `setNewLanguage()`, what parameters did you use.

**Comment by msayed-net** [comment]
You are using the latest version `4.1.1` correct!

Forgive me for the late response, I'm working on the next localization package (palestine_localization) with so many new features.

**Comment by msayed-net** [comment]
Please test different [versions](https://pub.dev/packages/localize_and_translate/versions) from the one you are using right now

**Comment by Abodysoma2021** [comment]
> Please test different [versions](https://pub.dev/packages/localize_and_translate/versions) from the one you are using right now

Yes I Have Change The Version To 4.0.0 And It Work Fine
Thanks
