### ISSUE TITLE
remove 404 from not found strings

### ISSUE THREAD

**Issue by mo-ah-dawood** [msayed-net/localize_and_translate#4]
at first this package is very good,

please remove 404 from the string if the key is not found 

### Why
in some cases i forgot to set the key in my json file so i need to use the default one
The good advantage for removing it is to allow us use a default strings may be just make one json file for Arabic and leave the English use  the default strings
note that the keys may be readable strings 
like this
` "Withdraw profits": "سحب الأرباح"`
now  if   the language is arabic the right side will be used
else the left will be used

**Comment by msayed-net** [comment]
Thanks for reaching out to me

Your suggestion considered and implemented in v2.0.10

Do not hesitate contacting me with any further enhancement suggestions.
